### ISSUE TITLE
Support for Fallback polymorphic types

### ISSUE THREAD

**Issue by cn-ml** [rmja/PolyJson#2]
Support for unspecified type discriminators would be very helpful for some use cases.

This would allow for something along the lines of this:

```
[PolyJsonConverter("type")]
[PolyJsonConverter.SubType(typeof(Derived), nameof(Derived))]
[PolyJsonConverter.FallbackType(typeof(Unknown))]
public abstract class Base { }
public class Derived : Base { }
public class Unknown : Base {
  [JsonPropertyName("type")
  public string Type { get; set; }
}
```

Initially I falsely assumed that this is exactly what the `DefaultType` was used for, but it seems that only catches the case if a discriminator is missing, right?

**Comment by rmja** [comment]
This is fixed in 1.3.0. Use `[PolyJsonConverter("_t", UnknownType = typeof(Unknown))]`
